# render.yaml

services:
  - type: web
    name: my-php-app
    env: php
    plan: free
    buildCommand: "" # No build command needed for basic PHP apps
    startCommand: "" # Render will automatically serve your PHP files
    envVars:
      - key: DATABASE_URL
        value: <your-database-url>
    # Add any other environment variables your app needs
